### ISSUE TITLE
Can't Get TicketActivity Based on Ticket ID

### ISSUE THREAD

**Issue by scrazzymoto** [Saleslogix/DotNetSDataClient#14]
Hi Nathan,

 I need to get the most recent ticket activity description for a particular ticket, but I won't actually have the ticket activity ID at the time of the query, I will only have the _ticket_ ID. I'm trying to do something like this:

  ```
class SDataHelper
{
      [SDataPath("tickets")]
        public class Ticket
        {
            [SDataProtocolProperty(SDataProtocolProperty.Key)]
            public string Id { get; set; }

            public Account Account { get; set; }
            public Contact Contact { get; set; }
            public TicketProblem TicketProblem { get; set; }

            public Urgency Urgency = new Urgency { };

            public string Subject { get; set; }
        }

        [SDataPath("ticketactivities")]
        public class TicketActivity
        {
            [SDataProtocolProperty(SDataProtocolProperty.Key)]
            public string Id { get; set; }

            public Ticket Ticket { get; set; }
            public Contact Contact { get; set; }

            public DateTime CreateDate { get; set; }

            public string ActivityDescription { get; set; }
        }

        public string GetTicketActivityDesc(Ticket ticket)
        {
            var query = _client.Query<TicketActivity>()
                .Where(T => T.Ticket == ticket)
                .OrderByDescending(T => T.CreateDate)
                .ToList<TicketActivity>();

            TicketActivity ticketActivity = null;

            if (query.Count > 0)
                ticketActivity = query[0];

            return ticketActivity.ActivityDescription;
        }
}
```

When I attempt this though, I get the following error:

Selector 'IntercomIntegration.SDataHelper+Ticket' not supported

**Comment by NathanBaulch** [comment]
You need to compare `ticket.Id` rather than the ticket objects themselves. Also, I'd recommend you use the LINQ `Select` and `FirstOrDefault` operators to limit the amount of information requested from the server. This will reduce the response to a single resource (`count=1`) containing a single property (`select=ActivityDescription`).

```csharp
var desc = _client.Query<TicketActivity>()
    .Where(t => t.Ticket.Key == ticket.Key)
    .OrderByDescending(t => t.CreateDate)
    .Select(t => t.ActivityDescription)
    .FirstOrDefault();
```

I might look into supporting direct resource comparisons (similar to NHibernate on the server-side) so I'll leave this issue open for now.

**Comment by scrazzymoto** [comment]
Sounds good, thank you! And I had also tried what you suggested, but now I see why mine wasn't working: I was trying to do 

`.Where(t => t.Ticket.Id == ticket.Id)`

And it was telling me it could resolve the field "Id." That's because it was called "Key" haha. Many thanks again!

**Comment by NathanBaulch** [comment]
`ticket.Id` should work equally well because it's mapped to `SDataProtocolProperty.Key` in your model. I just tested and it works for me.

**Comment by scrazzymoto** [comment]
Interesting. I'll have to look into it further. Thanks again.

**Comment by NathanBaulch** [comment]
Your original LINQ query with directly compared ticket objects should now work in version 2.0.1.1559.

**Comment by scrazzymoto** [comment]
Great, thanks Nathan!

**Comment by scrazzymoto** [comment]
Hi Nathan,
        Still experiencing the problem with the following:

` .Where(t => t.Ticket.Id == ticket.Id) `

Still getting the 

> could not resolve property: $key of: Sage.SalesLogix.Entities.Ticket.

I also updated to the newest version and tried to do it with the directly compared ticket objects:

` .Where(t => t.Ticket == ticket) `

I was also getting the same error. Any insight? Can't figure out where I'm going wrong.

**Comment by scrazzymoto** [comment]
Additional information: I traced the request back a bit through the code and found the URI:

[](http://slx8test/sData/slx/dynamic/-/ticketactivities?count=1&where=%28Ticket.%24key%20eq%20%27tPSFTA003377%27%29&orderBy=CreateSource%20desc&format=json)

**Comment by scrazzymoto** [comment]
Additional info: I traced the request back through some of your source code, and the error appears to be coming from how the request URI is being built. I pasted the URI into my browser and looked at it there. It appears to be two things. First, it is putting a %24 between "Ticket." and "key," so its looking for where "Ticket.$key = {id}," and it is saying it cannot resolve "$key." So, I removed the %24 from that bit, and it still can't resolve "key" (no '$' this time). So instead, I replaced "key" with the word "Id," and that worked. 

So here was how the source was building the URI: ...dynamic/-/ticketactivities?count=1&where=%28**Ticket.%24key**%20eq%20%27tPSFTA003377%27%29&orderBy=CreateSource%20desc&format=json

And here's what ended up working: ...dynamic/-/ticketactivities?count=1&where=%28**Ticket.Id**%20eq%20%27tPSFTA003377%27%29&orderBy=CreateSource%20desc&format=json

**Comment by NathanBaulch** [comment]
Not all SData servers support the `$key` protocol property in filter expressions. See this comment for a typical workaround: https://github.com/Saleslogix/DotNetSDataClient/pull/6#issuecomment-160647874

**Comment by scrazzymoto** [comment]
Fantastic! Thank you Nathan!
